--- #YAML:1.0
name:               Var-Extract
version:            0.02
abstract:           Assign lexical scalar values from container types
author:
    - M. Nunberg <mnunberg@haskalah.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    PadWalker:   0
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
